modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-CharcoalBlock/issues"
displayURL="http://curseforge.com/minecraft/mc-mods/sbm-charcoal-block"
authors="TheRealp455w0rd, DarkCow, bl4ckscor3"
license="MIT License https://github.com/BuiltBrokenModding/SBM-CharcoalBlock/blob/1.16/LICENSE"

[[mods]] #mandatory
modId="sbmcharcoalblock" #mandatory
version="v1.1.0" #mandatory
displayName="SBM-Charcoal Block" #mandatory
description='''Just adds a charcoal block''' #mandatory

[[dependencies.sbmcharcoalblock]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmcharcoalblock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"