modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-CharcoalBlock/issues"
license="MIT License https://github.com/BuiltBrokenModding/SBM-CharcoalBlock/blob/1.19/LICENSE"

[[mods]]
	modId="sbmcharcoalblock"
	version="${file.jarVersion}"
	displayName="SBM-Charcoal Block"
	description='''Just adds a charcoal block'''
	displayURL="http://curseforge.com/minecraft/mc-mods/sbm-charcoal-block"
	authors="TheRealp455w0rd, DarkCow, bl4ckscor3"

[[dependencies.sbmcharcoalblock]]
    modId="forge"
    mandatory=true
    versionRange="[44.0.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmcharcoalblock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"