modLoader="javafml" #mandatory
loaderVersion="[27,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-CharcoalBlock/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-charcoal-block"
authors="TheRealp455w0rd"

[[mods]] #mandatory
modId="sbmcharcoalblock" #mandatory
version="v1.0.0" #mandatory
displayName="SBM-Charcoal Block" #mandatory
description='''Just adds a charcoal block''' #mandatory

[[dependencies.sbmcharcoalblock]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmcharcoalblock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"